
USE tempdb
ALTER  DATABASE tempdb SET RECURSIVE_TRIGGERS  ON
DROP TABLE T
CREATE TABLE T
(
    a  INT,
    b  INT
)

INSERT INTO T VALUES(1, 1)

CREATE TRIGGER TR
ON T FOR UPDATE
AS
DECLARE @a INT, @b INT
SELECT @a = a, @b = b FROM T
IF @b < 100  UPDATE T SET a = @b, b = @a+@b 

UPDATE T SET a = 1
SELECT * FROM T
