
USE test;

DROP TABLE T1;
DROP TABLE T2;
DROP TABLE T3;

CREATE TABLE T1 (a  INT);
CREATE TABLE T2 (a  INT);
CREATE TABLE T3 (a  INT);

DELIMITER $$
CREATE TRIGGER TR1
AFTER INSERT ON T1 FOR EACH ROW
BEGIN
	DECLARE a1 INT;
	SELECT a INTO a1 FROM T1;
   INSERT INTO T2 VALUES(a1);
END$$

CREATE TRIGGER TR2
AFTER INSERT ON T2 FOR EACH ROW
BEGIN
	DECLARE a1 INT;
	DECLARE a2 INT;
	SELECT a INTO a1 FROM T1;
	SELECT a INTO a2 FROM T2;
   INSERT INTO T3 VALUES(a1 + a2);
END$$
DELIMITER ;

DROP TRIGGER TR1;
DROP TRIGGER TR2;
DROP TRIGGER TR3;

INSERT INTO T1 VALUES(98);

SELECT * FROM T3;
