g++ AbstractGeometricObject.cpp -o AbstractGeometricObject.exe
g++ AmbiguousOverloading.cpp -o AmbiguousOverloading.exe
g++ AppendFile.cpp -o AppendFile.exe
g++ ArrayPointer.cpp -o ArrayPointer.exe
g++ AssignGrade.cpp -o AssignGrade.exe
g++ BinaryArrayIO.cpp -o BinaryArrayIO.exe
g++ BinaryCharacterOutput.cpp -o BinaryCharacterOutput.exe
g++ BinaryCharInput.cpp -o BinaryCharInput.exe
g++ BinaryCharOutput.cpp -o BinaryCharOutput.exe
g++ BinaryIntInput.cpp -o BinaryIntInput.exe
g++ BinaryIntOutput.cpp -o BinaryIntOutput.exe
g++ BinaryIODemo.cpp -o BinaryIODemo.exe
g++ BinaryObjectIO.cpp -o BinaryObjectIO.exe
g++ BinarySearch.cpp -o BinarySearch.exe
g++ Calculator.cpp -o Calculator.exe
g++ ChainingDemo.cpp -o ChainingDemo.exe
g++ CharacterFunctions.cpp -o CharacterFunctions.exe
g++ CheckPalindrome.cpp -o CheckPalindrome.exe
g++ Circle.cpp -o Circle.exe
g++ Circle2.cpp -o Circle2.exe
g++ Circle3.cpp -o Circle3.exe
g++ Circle5.cpp -o Circle5.exe
g++ Circle6.cpp -o Circle6.exe
g++ CombineString.cpp -o CombineString.exe
g++ CompareString.cpp -o CompareString.exe
g++ ComputeArea.cpp -o ComputeArea.exe
g++ ComputeArea1.cpp -o ComputeArea1.exe
g++ ComputeArea2.cpp -o ComputeArea2.exe
g++ ComputeArea3.cpp -o ComputeArea3.exe
g++ ComputeArea4.cpp -o ComputeArea4.exe
g++ ComputeChange.cpp -o ComputeChange.exe
g++ ComputeFactorial.cpp -o ComputeFactorial.exe
g++ ComputeFibonacci.cpp -o ComputeFibonacci.exe
g++ ComputeLoan.cpp -o ComputeLoan.exe
g++ ComputeTax.cpp -o ComputeTax.exe
g++ ComputeTaxWithFunction.cpp -o ComputeTaxWithFunction.exe
g++ ComputeTaxWithSelectionStatement.cpp -o ComputeTaxWithSelectionStatement.exe
g++ ConstArrayDemo.cpp -o ConstArrayDemo.exe
g++ ConstIteratorDemo.cpp -o ConstIteratorDemo.exe
g++ ConstParameter.cpp -o ConstParameter.exe
g++ ConstParamter.cpp -o ConstParamter.exe
g++ CopyConstructorDemo.cpp -o CopyConstructorDemo.exe
g++ CopyDemo.cpp -o CopyDemo.exe
g++ CopyFile.cpp -o CopyFile.exe
g++ CopyObject.cpp -o CopyObject.exe
g++ CopyString.cpp -o CopyString.exe
g++ CorrectReverse.cpp -o CorrectReverse.exe
g++ CountDemo.cpp -o CountDemo.exe
g++ CountLettersInArray.cpp -o CountLettersInArray.exe
g++ Course.cpp -o Course.exe
g++ CreateLargeFile.cpp -o CreateLargeFile.exe
g++ CustomCopyConstructor.cpp -o CustomCopyConstructor.exe
g++ Date.cpp -o Date.exe
g++ DefaultArgumentDemo.cpp -o DefaultArgumentDemo.exe
g++ DefaultAssignmentDemo.cpp -o DefaultAssignmentDemo.exe
g++ DequeDemo.cpp -o DequeDemo.exe
g++ DerivedCircle.cpp -o DerivedCircle.exe
g++ DerivedCircle2.cpp -o DerivedCircle2.exe
g++ DisplayTime.cpp -o DisplayTime.exe
g++ DynamicCastingDemo.cpp -o DynamicCastingDemo.exe
g++ EnterIntegers.cpp -o EnterIntegers.exe
g++ EvenOrOdd.cpp -o EvenOrOdd.exe
g++ ExceptionDemo1.cpp -o ExceptionDemo1.exe
g++ ExceptionDemo2.cpp -o ExceptionDemo2.exe
g++ ExceptionDemo3.cpp -o ExceptionDemo3.exe
g++ FahrenheitToCelsius.cpp -o FahrenheitToCelsius.exe
g++ File1.cpp -o File1.exe
g++ File2.cpp -o File2.exe
g++ FillDemo.cpp -o FillDemo.exe
g++ FindDemo.cpp -o FindDemo.exe
g++ FindElement.cpp -o FindElement.exe
g++ FindEndDemo.cpp -o FindEndDemo.exe
g++ FindFirstOf.cpp -o FindFirstOf.exe
g++ FindSalesAmount.cpp -o FindSalesAmount.exe
g++ ForEachDemo.cpp -o ForEachDemo.exe
g++ FormattedDataOutput.cpp -o FormattedDataOutput.exe
g++ GenerateDemo.cpp -o GenerateDemo.exe
g++ GenericMaxValue.cpp -o GenericMaxValue.exe
g++ GenericSort.cpp -o GenericSort.exe
g++ GeometricObject.cpp -o GeometricObject.exe
g++ GradeExam.cpp -o GradeExam.exe
g++ GreatestCommonDivisor.cpp -o GreatestCommonDivisor.exe
g++ GuessBirthDate.cpp -o GuessBirthDate.exe
g++ GuessBirthDateUsingArray.cpp -o GuessBirthDateUsingArray.exe
g++ HideDataField.cpp -o HideDataField.exe
g++ Increment.cpp -o Increment.exe
g++ InlineDemo.cpp -o InlineDemo.exe
g++ InlineDemo1.cpp -o InlineDemo1.exe
g++ InlineDemo2.cpp -o InlineDemo2.exe
g++ InputOutputStreamIteratorDemo.cpp -o InputOutputStreamIteratorDemo.exe
g++ insertionSort.cpp -o insertionSort.exe
g++ IteratorDemo.cpp -o IteratorDemo.exe
g++ IteratorOperatorDemo.cpp -o IteratorOperatorDemo.exe
g++ LeapYear.cpp -o LeapYear.exe
g++ LinearSearch.cpp -o LinearSearch.exe
g++ ListDemo.cpp -o ListDemo.exe
g++ Loan.cpp -o Loan.exe
g++ MapDemo.cpp -o MapDemo.exe
g++ MathOperationDemo.cpp -o MathOperationDemo.exe
g++ MaxMinDemo.cpp -o MaxMinDemo.exe
g++ MergeDemo.cpp -o MergeDemo.exe
g++ ModifyArray.cpp -o ModifyArray.exe
g++ MultipleCatchDemo.cpp -o MultipleCatchDemo.exe
g++ MultipleInheritanceDemo.cpp -o MultipleInheritanceDemo.exe
g++ NamespaceDemo.cpp -o NamespaceDemo.exe
g++ NewRational.cpp -o NewRational.exe
g++ NoDefaultConstructor1.cpp -o NoDefaultConstructor1.exe
g++ NoDefaultConstructor2.cpp -o NoDefaultConstructor2.exe
g++ OperatorKeywordDemo.cpp -o OperatorKeywordDemo.exe
g++ PassArrayDemo.cpp -o PassArrayDemo.exe
g++ PassByReferenceDemo.cpp -o PassByReferenceDemo.exe
g++ PassObject.cpp -o PassObject.exe
g++ PassObjectByReference.cpp -o PassObjectByReference.exe
g++ PassObjectByValue.cpp -o PassObjectByValue.exe
g++ PassObjectToPointer.cpp -o PassObjectToPointer.exe
g++ PassTwoDimensionalArray.cpp -o PassTwoDimensionalArray.exe
g++ Person.cpp -o Person.exe
g++ Person1.cpp -o Person1.exe
g++ PointerWithIndex.cpp -o PointerWithIndex.exe
g++ PolymorphismDemo.cpp -o PolymorphismDemo.exe
g++ PrimeNumber.cpp -o PrimeNumber.exe
g++ PrintCalendar.cpp -o PrintCalendar.exe
g++ PrintPyramid.cpp -o PrintPyramid.exe
g++ PriorityQueueDemo.cpp -o PriorityQueueDemo.exe
g++ QueueDemo.cpp -o QueueDemo.exe
g++ Quotient.cpp -o Quotient.exe
g++ QuotientWithException.cpp -o QuotientWithException.exe
g++ QuotientWithFunction.cpp -o QuotientWithFunction.exe
g++ QuotientWithIf.cpp -o QuotientWithIf.exe
g++ RandomAccessFile.cpp -o RandomAccessFile.exe
g++ Rational.cpp -o Rational.exe
g++ ReadAllData.cpp -o ReadAllData.exe
g++ ReadCity.cpp -o ReadCity.exe
g++ ReadData.cpp -o ReadData.exe
g++ ReadSortedLargeFile.cpp -o ReadSortedLargeFile.exe
g++ ReadState.cpp -o ReadState.exe
g++ Rectangle.cpp -o Rectangle.exe
g++ Rectangle2.cpp -o Rectangle2.exe
g++ RecursiveBinarySearch.cpp -o RecursiveBinarySearch.exe
g++ RecursivePalindrome1.cpp -o RecursivePalindrome1.exe
g++ RecursivePalindrome2.cpp -o RecursivePalindrome2.exe
g++ RecursiveSelectionSort.cpp -o RecursiveSelectionSort.exe
g++ RemoveCopyDemo.cpp -o RemoveCopyDemo.exe
g++ RemoveDemo.cpp -o RemoveDemo.exe
g++ ReplaceCopyDemo.cpp -o ReplaceCopyDemo.exe
g++ ReplaceDemo.cpp -o ReplaceDemo.exe
g++ RethrowExceptionDemo.cpp -o RethrowExceptionDemo.exe
g++ ReverseArray.cpp -o ReverseArray.exe
g++ ReverseDemo.cpp -o ReverseDemo.exe
g++ ReverseIteratorDemo.cpp -o ReverseIteratorDemo.exe
g++ RotateDemo.cpp -o RotateDemo.exe
g++ SalesTax.cpp -o SalesTax.exe
g++ SearchDemo.cpp -o SearchDemo.exe
g++ SelectionSort.cpp -o SelectionSort.exe
g++ SentinelValue.cpp -o SentinelValue.exe
g++ SetDemo.cpp -o SetDemo.exe
g++ SetOperationDemo.cpp -o SetOperationDemo.exe
g++ ShallowCopyDemo.cpp -o ShallowCopyDemo.exe
g++ ShowCurrentTime.cpp -o ShowCurrentTime.exe
g++ ShowStreamState.cpp -o ShowStreamState.exe
g++ ShowSyntaxErrors.cpp -o ShowSyntaxErrors.exe
g++ ShuffleDemo.cpp -o ShuffleDemo.exe
g++ SimpleFileInput.cpp -o SimpleFileInput.exe
g++ SimpleFileOutput.cpp -o SimpleFileOutput.exe
g++ SimpleSTLDemo.cpp -o SimpleSTLDemo.exe
g++ SortDemo.cpp -o SortDemo.exe
g++ SortLargeFile.cpp -o SortLargeFile.exe
g++ StackDemo.cpp -o StackDemo.exe
g++ StackOfIntegers.cpp -o StackOfIntegers.exe
g++ StaticVariableDemo.cpp -o StaticVariableDemo.exe
g++ StreamState.cpp -o StreamState.exe
g++ StringConversion.cpp -o StringConversion.exe
g++ Student.cpp -o Student.exe
g++ SubtractionTutor.cpp -o SubtractionTutor.exe
g++ SubtractionTutorLoop.cpp -o SubtractionTutorLoop.exe
g++ SwapArrayElements.cpp -o SwapArrayElements.exe
g++ SwapDemo.cpp -o SwapDemo.exe
g++ Temp.cpp -o Temp.exe
g++ Test.cpp -o Test.exe
g++ Test1.cpp -o Test1.exe
g++ TestArray.cpp -o TestArray.exe
g++ TestBinaryTree.cpp -o TestBinaryTree.exe
g++ TestBoolean.cpp -o TestBoolean.exe
g++ TestBooleanOperators.cpp -o TestBooleanOperators.exe
g++ TestBreak.cpp -o TestBreak.exe
g++ TestCircle.cpp -o TestCircle.exe
g++ TestCircle2.cpp -o TestCircle2.exe
g++ TestCircle5.cpp -o TestCircle5.exe
g++ TestCircle6.cpp -o TestCircle6.exe
g++ TestCircleWithInterface.cpp -o TestCircleWithInterface.exe
g++ TestContinue.cpp -o TestContinue.exe
g++ TestCourse.cpp -o TestCourse.exe
g++ TestDo.cpp -o TestDo.exe
g++ TestEndofFile.cpp -o TestEndofFile.exe
g++ TestEnumeratedType.cpp -o TestEnumeratedType.exe
g++ TestFriendClass.cpp -o TestFriendClass.exe
g++ TestFriendFunction.cpp -o TestFriendFunction.exe
g++ TestFrientClass.cpp -o TestFrientClass.exe
g++ TestFunctionOverloading.cpp -o TestFunctionOverloading.exe
g++ TestFunctionPrototype.cpp -o TestFunctionPrototype.exe
g++ TestGenericStack.cpp -o TestGenericStack.exe
g++ TestGenericStack1.cpp -o TestGenericStack1.exe
g++ TestGeometricObject.cpp -o TestGeometricObject.exe
g++ TestGeometricObject2.cpp -o TestGeometricObject2.exe
g++ TestHeap.cpp -o TestHeap.exe
g++ TestHeapSort.cpp -o TestHeapSort.exe
g++ TestIterator.cpp -o TestIterator.exe
g++ TestLinkedList.cpp -o TestLinkedList.exe
g++ TestList.cpp -o TestList.exe
g++ TestLoanClass.cpp -o TestLoanClass.exe
g++ TestLogicalOperators.cpp -o TestLogicalOperators.exe
g++ TestMax.cpp -o TestMax.exe
g++ TestMultiplicationTable.cpp -o TestMultiplicationTable.exe
g++ TestMyLib.cpp -o TestMyLib.exe
g++ TestNewRationalClass.cpp -o TestNewRationalClass.exe
g++ TestPassByReference.cpp -o TestPassByReference.exe
g++ TestPassByValue.cpp -o TestPassByValue.exe
g++ TestPassObject.cpp -o TestPassObject.exe
g++ TestPerson.cpp -o TestPerson.exe
g++ TestPerson1.cpp -o TestPerson1.exe
g++ TestPointer.cpp -o TestPointer.exe
g++ TestPointerArgument.cpp -o TestPointerArgument.exe
g++ TestPriorityQueue.cpp -o TestPriorityQueue.exe
g++ TestQueue.cpp -o TestQueue.exe
g++ TestRandomCharacter.cpp -o TestRandomCharacter.exe
g++ TestRationalClass.cpp -o TestRationalClass.exe
g++ TestReferenceVariable.cpp -o TestReferenceVariable.exe
g++ TestStackOfIntegers.cpp -o TestStackOfIntegers.exe
g++ TestStackWithLinkedList.cpp -o TestStackWithLinkedList.exe
g++ TestStudent.cpp -o TestStudent.exe
g++ TestStudent1.cpp -o TestStudent1.exe
g++ TestSubstring.cpp -o TestSubstring.exe
g++ TestSum.cpp -o TestSum.exe
g++ TestTriangle.cpp -o TestTriangle.exe
g++ TestVector.cpp -o TestVector.exe
g++ TestVoidFunction.cpp -o TestVoidFunction.exe
g++ TextFileInput.cpp -o TextFileInput.exe
g++ TextFileOutput.cpp -o TextFileOutput.exe
g++ TotalArea.cpp -o TotalArea.exe
g++ TotalScore.cpp -o TotalScore.exe
g++ TowersOfHanoi.cpp -o TowersOfHanoi.exe
g++ UpdateFile.cpp -o UpdateFile.exe
g++ UseMyLib.cpp -o UseMyLib.exe
g++ VariableScopeDemo.cpp -o VariableScopeDemo.exe
g++ VectorDemo.cpp -o VectorDemo.exe
g++ VisibilityDemo.cpp -o VisibilityDemo.exe
g++ Welcome.cpp -o Welcome.exe
g++ Welcome1.cpp -o Welcome1.exe
g++ WhyPolymorphismDemo.cpp -o WhyPolymorphismDemo.exe
g++ WriteData.cpp -o WriteData.exe
g++ WriteFormatData.cpp -o WriteFormatData.exe
g++ WrongReverse.cpp -o WrongReverse.exe
